"""added data in tables

Revision ID: 1aa14c86425b
Revises: 406fd6746783
Create Date: 2023-06-07 20:59:06.061291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa14c86425b'
down_revision = '406fd6746783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
