"""added data in tables

Revision ID: 2eb0453191d5
Revises: 87b260e86bdd
Create Date: 2023-06-07 19:58:36.167820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb0453191d5'
down_revision = '87b260e86bdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
