"""added data in tables

Revision ID: 406fd6746783
Revises: 2eb0453191d5
Create Date: 2023-06-07 20:20:19.618794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406fd6746783'
down_revision = '2eb0453191d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
