"""added data in tables

Revision ID: 87b260e86bdd
Revises: 52aa23bd7a67
Create Date: 2023-06-07 19:54:54.046671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b260e86bdd'
down_revision = '52aa23bd7a67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('grade_in', sa.Integer(), nullable=True))
    op.drop_column('students', 'class_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_in', sa.INTEGER(), nullable=True))
    op.drop_column('students', 'grade_in')
    # ### end Alembic commands ###
